
SOURCES += projectWidget/projectwidget.cpp \
    $$PWD/bgmnpresethandlergui.cpp \
    $$PWD/bgmnsinglepeakrefinementdialog.cpp \
    $$PWD/graphWidget/abstractgraphview.cpp \
    $$PWD/graphWidget/graphwindowkeyeventhandler.cpp \
    $$PWD/graphWidget/graphwindowlegend.cpp \
    $$PWD/msoExport/msoeditexcelexportdialog.cpp \
    $$PWD/msoExport/msoexportexcel.cpp \
    $$PWD/peakFitWidget/peakfitcurve.cpp \
    $$PWD/peakFitWidget/peakfititem.cpp \
    $$PWD/peakFitWidget/peakfitparameter.cpp \
    $$PWD/peakFitWidget/peakfitrange.cpp \
    $$PWD/peakFitWidget/peakfitvariable.cpp \
    $$PWD/peakFitWidget/peakfitwidget.cpp \
    $$PWD/peakListWidget/hklsortfilterproxymodel.cpp \
    $$PWD/peakListWidget/peaklistfilterform.cpp \
    $$PWD/peakListWidget/peaklistfilterhkldelegate.cpp \
    $$PWD/peakListWidget/peaklistfilterdoubledelegate.cpp \
    $$PWD/peakListWidget/peaklistfilteritemhkl.cpp \
    $$PWD/peakListWidget/peaklistfilteritemdouble.cpp \
    $$PWD/presetcontentsavedialog.cpp \
    $$PWD/projectselecttreeitem.cpp \
    $$PWD/scanListWidget/scanlistwidgetdelegate.cpp \
    $$PWD/scanListWidget/scanlistwidgetitem.cpp \
    projectWidget/fphandler.cpp \
    projectWidget/fpprojectwidget.cpp \
    projectWidget/bgmnprojectwidget.cpp \
    projectWidget/bgmnhandler.cpp \
    projectWidget/processhandler.cpp \
    projectWidget/controlfileedit.cpp \
    projectWidget/graphWidget/graphwindow.cpp \
    $$PWD/chemTable/chemtablewidget.cpp \
    projectWidget/scanListWidget/scanlistwidget.cpp \
    projectWidget/peakintegrationwidget.cpp \
    projectWidget/convergencedisplay.cpp \
    projectWidget/bgmnaddremovedialog.cpp \
    projectWidget/fpaddremovedialog.cpp \
    projectWidget/syntaxHighlighter/bgmnhighlighter.cpp \
    projectWidget/syntaxHighlighter/fphighlighter.cpp \
    projectWidget/filepoller/bgmndiahandler2.cpp \
    projectWidget/bgmnrefstructuremanager.cpp \
    projectWidget/bgmnindexingerrordialog.cpp \
    projectWidget/bgmnbackendconfig.cpp \
    projectWidget/gentemplatedialog.cpp \
    projectWidget/internalstandarddialog.cpp \
    projectWidget/eflechhandler.cpp \
    $$PWD/strfilebatcheditdialog.cpp \
    $$PWD/bgmninstrumentselectdialog.cpp \
    $$PWD/peakListWidget/peaklistwidget.cpp \
    $$PWD/resultsTreeWidget/resultstreewidget.cpp \
    $$PWD/resultsTreeWidget/bgmnresultstreewidget.cpp \
    $$PWD/resultsTreeWidget/fpresultstreewidget.cpp \
    $$PWD/graphWidget/graphdatamodel.cpp \
    $$PWD/graphWidget/graphdatacontroller.cpp \
    $$PWD/bgmnstrindexer.cpp \
    $$PWD/indexedhklstructure.cpp \
    $$PWD/bgmnstrverifier.cpp

HEADERS += projectWidget/projectwidget.h \
    $$PWD/bgmnpresethandlergui.h \
    $$PWD/bgmnsinglepeakrefinementdialog.h \
    $$PWD/graphWidget/abstractgraphview.h \
    $$PWD/graphWidget/graphwindowkeyeventhandler.h \
    $$PWD/graphWidget/graphwindowlegend.h \
    $$PWD/msoExport/msoeditexcelexportdialog.h \
    $$PWD/msoExport/msoexportexcel.h \
    $$PWD/peakFitWidget/peakfitcurve.h \
    $$PWD/peakFitWidget/peakfititem.h \
    $$PWD/peakFitWidget/peakfitparameter.h \
    $$PWD/peakFitWidget/peakfitrange.h \
    $$PWD/peakFitWidget/peakfitvariable.h \
    $$PWD/peakFitWidget/peakfitwidget.h \
    $$PWD/peakListWidget/hklsortfilterproxymodel.h \
    $$PWD/peakListWidget/peaklistfilterform.h \
    $$PWD/peakListWidget/peaklistfilterhkldelegate.h \
    $$PWD/peakListWidget/peaklistfilterdoubledelegate.h \
    $$PWD/peakListWidget/peaklistfilteritemhkl.h \
    $$PWD/peakListWidget/peaklistfilteritemdouble.h \
    $$PWD/presetcontentsavedialog.h \
    $$PWD/projectselecttreeitem.h \
    $$PWD/scanListWidget/scanlistwidgetdelegate.h \
    $$PWD/scanListWidget/scanlistwidgetitem.h \
    projectWidget/fphandler.h \
    projectWidget/fpprojectwidget.h \
    projectWidget/bgmnprojectwidget.h \
    projectWidget/bgmnhandler.h \
    projectWidget/processhandler.h \
    projectWidget/controlfileedit.h \
    projectWidget/graphWidget/graphwindow.h \
    $$PWD/chemTable/chemtablewidget.h \
    projectWidget/scanListWidget/scanlistwidget.h \
    projectWidget/peakintegrationwidget.h \
    projectWidget/convergencedisplay.h \
    projectWidget/bgmnaddremovedialog.h \
    projectWidget/fpaddremovedialog.h \
    projectWidget/syntaxHighlighter/bgmnhighlighter.h \
    projectWidget/syntaxHighlighter/fphighlighter.h \
    projectWidget/filepoller/bgmndiahandler2.h \
    projectWidget/bgmnrefstructuremanager.h \
    projectWidget/bgmnindexingerrordialog.h \
    projectWidget/bgmnbackendconfig.h \
    projectWidget/gentemplatedialog.h \
    projectWidget/internalstandarddialog.h \
    projectWidget/eflechhandler.h \
    $$PWD/strfilebatcheditdialog.h \
    $$PWD/bgmninstrumentselectdialog.h \
    $$PWD/peakListWidget/peaklistwidget.h \
    $$PWD/resultsTreeWidget/resultstreewidget.h \
    $$PWD/resultsTreeWidget/bgmnresultstreewidget.h \
    $$PWD/resultsTreeWidget/fpresultstreewidget.h \
    $$PWD/graphWidget/graphdatamodel.h \
    $$PWD/graphWidget/graphdatacontroller.h \
    $$PWD/bgmnstrindexer.h \
    $$PWD/indexedhklstructure.h \
    $$PWD/bgmnstrverifier.h

FORMS += projectWidget/bgmnindexingerrordialog.ui \
    $$PWD/bgmnsinglepeakrefinementdialog.ui \
    $$PWD/msoExport/msoeditexcelexportdialog.ui \
    $$PWD/peakFitWidget/peakfitwidget.ui \
    $$PWD/peakintegrationwidget.ui \
    $$PWD/presetcontentsavedialog.ui \
    projectWidget/gentemplatedialog.ui \
    projectWidget/internalstandarddialog.ui \
    $$PWD/strfilebatcheditdialog.ui \
    $$PWD/bgmninstrumentselectdialog.ui \
    $$PWD/peakListWidget/peaklistwidget.ui \
    $$PWD/chemTable/chemtablewidgetform.ui
